// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLsCrieEnukOi9Do0J9vuqm3a839MLsc',
    appId: '1:506731571370:android:d6c69b1c33b6b725c088d3',
    messagingSenderId: '506731571370',
    projectId: 'fushati-pay-4ee38',
    databaseURL: 'https://fushati-pay-4ee38-default-rtdb.firebaseio.com',
    storageBucket: 'fushati-pay-4ee38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP_Iz4S8diyaA9-1tCIRm5Qj-tav1daSk',
    appId: '1:506731571370:ios:6e82ff8039aae177c088d3',
    messagingSenderId: '506731571370',
    projectId: 'fushati-pay-4ee38',
    databaseURL: 'https://fushati-pay-4ee38-default-rtdb.firebaseio.com',
    storageBucket: 'fushati-pay-4ee38.appspot.com',
    iosBundleId: 'com.fushati.parents',
  );
}
